# Generated by Django 5.2.17 on 2026-09-12 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('payer', models.CharField(blank=True, max_length=200)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('billed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('denial_reason', models.CharField(blank=True, choices=[('not_covered', 'Service not covered'), ('duplicate', 'Duplicate claim'), ('insufficient_documentation', 'Insufficient documentation'), ('out_of_network', 'Out of network'), ('timely_filing', 'Timely filing limit exceeded')], max_length=32)),
                ('state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUESTED', 'Info requested'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=0)),
                ('submission_id', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUESTED', 'Info requested'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('to_state', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INFO_REQUESTED', 'Info requested'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('alert', 'Alert')], default='info', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claim_events', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='claims.claim')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), models.Q(('approved_amount__gt', 0), ('approved_amount__lte', models.F('billed_amount'))), _connector='OR'), name='claim_approved_within_billed'),
        ),
    ]
