# Generated by Django 5.2.17 on 2026-09-13 17:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claimevent_immutable'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='has_open_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_FLIGHT', 'In flight'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('HALTED', 'Halted')], default='PENDING', max_length=12)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('in_flight_since', models.DateTimeField(blank=True, null=True)),
                ('lease_token', models.CharField(blank=True, max_length=32)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='registration', to='claims.claim')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='registration_due_idx')],
            },
        ),
    ]
