# Generated by Django 5.2.17 on 2026-09-14 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_FLIGHT', 'In flight'), ('UNCERTAIN', 'Needs reconciliation'), ('DONE', 'Done'), ('FAILED', 'Failed'), ('HALTED', 'Halted')], default='PENDING', max_length=12),
        ),
    ]
